language: r
r:
  - oldrel 
  - release
dist: trusty
sudo: required
before_install:
  - sudo apt-get install libv8-dev
  - sudo apt-get install libudunits2-dev
r_packages:
  - devtools
 
 r_github_packages:
  - kwb-r/kwb.utils
