language: r
r:
  - oldrel 
  - release
dist: trusty
sudo: required
before_install:
  - sudo apt-get install libv8-dev
  - sudo apt-get install libudunits2-dev
r_packages:
  - devtools
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
