#
# This test file has been generated by kwb.test::create_test_files()
#

### Disable test which fails on Travis
# test_that("import_data_berlin_s() works", {
#
#   aquanes.report:::import_data_berlin_s()
# })

