#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("calculate_operational_parameters_berlin_s() works", {

  expect_error(aquanes.report:::calculate_operational_parameters_berlin_s())
})

