---
title: "3.1 GUI Explore panel"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{3.1 GUI explore panel}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The explore panel enables the user to: 

-	Inspect online and offline data using different 

-	Temporal aggregation levels (raw; median values for 10min, 1hour, 1day) and 
also enables 

-	Data export

All available features are described in detail in the following sub-chapters.

## 3.1 Select temporal aggregation

The “selection temporal aggregation” input menu offers four different options as 
shown below: 
 
Figure 3  Select temporal aggregation (default setting)

Only in case of “raw” no temporal aggregation is performed and just the raw data 
will be returned. However, this can be quite time consuming in case of large data 
amounts.  

All other options perform a temporal aggregation of the underlying data by 
calculating the median values for all parameters for 10 minutes (selection: 
“10min”), hourly (selection: “hour”) or daily (se-lection: “day”) time periods. 

By default the R reporting tool aggregates the parameter values as 10 minutes 
median values.  

## 3.2 Select a time zone
By default all data are presented in UTC. However, it is also possible to 
transform the time zone to the site`s local time (i.e. Asia/Calcutta) as shown 
below in Figure 4.
 
Figure 4  Select a time zone (default setting)

## 3.3 Select date range
By default the date range starts on 2016-09-05 and ends on 2016-10-31 as shown 
below in Figure 5.

 
Figure 5  Select a date range (default setting)
However, the date range can be changed easily by clicking with the mouse into 
the start/end field, which in turn opens a calender for specifying new start/end 
date as shown below in Figure 6.
        
Figure 6  Select a date range (change the default setting)

## 3.4 Fix date range 
The checkbox option Fix daterange (Figure 7) is important if you interactively 
zoom in your plots. 
 
Figure 7  Fix daterange (default setting)


In case the Fix daterange option is disabled (default setting, see Figure 7 
above) and you zoom to a specific period (e.g. ~ 2016-10-10 – ~ 2016-10-11 as 
shown in Figure 8), the zoom level will be lost (Figure 9) if you change your 
parameterisation afterwards (e.g. switching from “10min” to “hour” values). 
 
Figure 8  Interactive zoom to user defined period (~2016-10-10 to ~2016-10-11)
 
Figure 9 Plot with disabled “Fix daterange”: changed temporal aggregation (“hour”) 

For avoiding this behaviour you need to enable the Fix daterange checkbox and 
your selected zoom level will survive even if you change the parameterisation 
afterwards as shown in Figure 10.

 
Figure 10 Plot with enabled “Fix daterange”: changed temporal aggregation (“hour”) 

## 3.5 Select sampling point(s)
By default all available sampling points are selected, as shown below in Figure 13.
 
Figure 11  Select a sampling point (default setting)


In case you want to remove sampling points you need to mark them (by pressing 
Ctrl and clicking on them with the mouse, see Figure 12, left) and subsequently 
you can delete them by pressing the De-lete button on your keyboard. The deleted 
sampling points are still available in a drop down menu (see Figure 12, right), 
where they can be easily added again (i.e. by selecting them with the mouse).

     

## 3.6 Select parameter(s) for plot 1/2
By default one parameter for each plot is pre-selected (i.e. battery voltage for 
plot1 and total chlorine for plot2), as shown below in Figure 13.
 
Figure 13  Select parameter(s) for plot 1/2 (default setting)

One the one hand it is possible to select a different parameter for each plot 
(based on the available online/offline parameters for the Haridwar site in the 
dropdown list) as shown in Figure 14 below: 
    
Figure 14  Select parameter(s) for plot 1/2 (change default setting)

On the other hand it is also possible to select multiple parameters for one plot. 
However, in the latter case plotting multiple parameters with completely different 
data value ranges (e.g. parameter1: 0 – 1, parameter2: 100-10000 should be avoided).

## 3.7 Add thresholds to plot 1+2
By default thresholds parameters are added to both plots (Figure 15). This 
feature can be disabled by unchecking the checkbox. In the latter case no 
horizontal lines will be plotted if a selected parameter has a pre-defined 
threshold.
 
Figure 15  Add thresholds to plots 1+2 (default setting)


**Note:**
***The thresholds can be modified by the user, which is described in Chapter XXXX***

## 3.8 Download options

There are two different download options available: 

-	Download data: download the entire dataset of plot 1 or 2 as CSV with the 
selected temporal aggregation level (see [Select temporal aggregation](#select-temporal-aggregation)), time zone (see [Select a time zone](#select-a-time-zone) and date range (see [Select date range](#select-date-range)) 
at all selected sampling points (see [Select sampling point(s)](#select-sampling-point-s)) 
for the parameters in plot 1 or 2 (see [Select parameter(s) for plot 1/2](#select-parameter-s-for-plot-1-2)), respectively. 

-	Download plot: downloads plot 1 and 2 as HTML document (including all data 
points). This document still contains interactive zooming for the selected 
dataset and can be send as stand-alone HTML document via email.

